### ISSUE TITLE
Questions regarding this crate

### ISSUE THREAD

**Issue by Joe23232** [rust-embedded/embedded-hal#315]
Hi there, I have some questions regarding this crate:
1. For an Arduino, what benefits do I get from using this crate as opposed to writing it using Arduino's native C++ library?
2. Is this a "write once run anywhere" sort of crate, where I could write code up for an Arduino using AVR processor and then run the same on an Arduino using SAMD processor?

Can the same code be ported over to a Rasbperry Pi or even other similar minicomputers such as Orange Pi and Odroid?
3. Can I please get a sample code in regards to simply flashing an LED light?
4. Are there any documentations?
5. Once when stable `1.0.0` is released, would it support as much devices as the Raspberry/Arduino supports?

**Comment by therealprof** [comment]
This crate defines an interface between common peripherals and their users (either drivers or applications). It doesn't contain specific implementations for specific hardware, those are elsewhere. I'm not keeping track of all individual implementations but since you asked about a Rasperry Pi and similar, there's an implementation of the interfaces defined in this crate for all kinds of Linux based embedded devices here: `https://github.com/rust-embedded/linux-embedded-hal`.

The interfaces allow you to write (and use) universal drivers which work on every system which provides an implementation of the traits. It does **not** allow you to write applications which work on any hardware without modification. If you're interested in finding specific implementations, drivers and example code I'd recommend you have a look at https://github.com/rust-embedded/awesome-embedded-rust where a lot of them are referenced.
