### ISSUE TITLE
Why is there no spi::blocking::Read trait

### ISSUE THREAD

**Issue by peckpeck** [rust-embedded/embedded-hal#417]
There is a blocking write trait, but it looks to me that the read is missing

**Comment by Dirbaio** [comment]
The upcoming embedded-hal 1.0 does have SPI read. 

In 0.2 you can use `transfer` with a zerofilled buffer.

**Comment by peckpeck** [comment]
Thank you
as for transfer, it seems to only work if there are as many bytes sent as received (or it is not well documented enough)

**Comment by adamgreig** [comment]
That's right (at least in the current 0.2 version of embedded-hal). It's because SPI must always send as many bytes as it receives. You can just put dummy bytes to make sure you read as much as you want (and remember the first bytes "received" will be during the initial transmission, so you probably want to discard them).

**Comment by peckpeck** [comment]
i'm not sure the spi peripheral i'm using respects this kind of rule
but as long as what i need is in the next version, all is good for me
