### ISSUE TITLE
Implment `Clone` for async DelayNs

### ISSUE THREAD

**Issue by PegasisForever** [rust-embedded/embedded-hal#596]
Currently [`DelayNs` Trait](https://github.com/rust-embedded/embedded-hal/blob/a0ccb6579669804e9be723912ed645a16362c8a6/embedded-hal-async/src/delay.rs#L4) doesn't implement Clone or Copy, which makes the following pattern not possible:

```rust
async fn main_task(mut delay: impl DelayNs){
    let fut1 = task1(&mut delay);
    let fut2 = task2(&mut delay); // Error: cannot borrow `delay` as mutable more than once at a time

    join(fut1, fut2).await;
}

async fn task1(delay: &mut impl DelayNs){
    delay.delay_ms(1).await;
    // do something
}

async fn task2(delay: &mut impl DelayNs){
    delay.delay_ms(1).await;
    // do something
}
```

I believe this is an common pattern in async (spawning multiple tasks and waiting for them to complete). Is there a way around this?

**Comment by Dirbaio** [comment]
Not all implementations can be cloned. Impls that directly use a hardware timer, for example. So i'm not sure we want this.

You can still choose to require cloneable delays in generic code by doing `where T: DelayNs + Clone` or `impl DelayNs + Clone`. 

Anyway, we can't add the `: Clone` bound now because it'd be a breaking change. Even if we decided we want this, it'd have to wait until embedded-hal 2.0, which is not happening anytime soon.

**Comment by PegasisForever** [comment]
thanks!
